### PR TITLE
added models.md and models.yml

### LINKED ISSUE #62: Add models page
Like resources page, there should be a models page which lists useful models (pretrained or not) that could me applied to medical tasks.

One example is DINO https://github.com/facebookresearch/dino

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
added a model page. I created a .md and a .yml document and placed them in their respective folders.

### CODE REVIEW

**Comment by hshuaib90** [comment]
Thanks, Lucrezia. How does a visitor find this webpage through navigation? Also how will the yaml be rendered in the models page? Will it be in a table or something else? There will need to be an associate layouts file or something in the Markdown document itself.

**Comment by Lucrezia-Cester** [comment]
I added the position from where this will be found in the webpae.

**Review by dangerdika — CHANGES_REQUESTED** [review]
As we just discussed, you need to add a models.html to _layouts and think of the way this data should be presented (resources page has a different structure but is a good starting point)

**Comment by Lucrezia-Cester** [comment]
Hi Dika, the new models.html renders the models.yml correctly now.

**Review by dangerdika — APPROVED** [review]
Renders well for me now, perfect! Thanks Lu! Approved.

**Pull request merged**
