### PR TITLE
Broken team member hyperlinks now link to /team.html

### PR DESCRIPTION
**Pull request by alexandertdeng**
All team member hyperlinks on project pages were broken because they pointed to non-existent pages.
1. Changed all broken team hyperlinks to point to /team.html
2. Changed project template to reflect (1)
3. Deleted directory "team', as it only contained empty files. Team member information is stored elsewhere.

### CODE REVIEW

**Comment by dangerdika** [comment]
@hshuaib90 what was the long term plan for team pages, were we to have a page each with a bit about us and what we focus on, or is the team page enough? I think we should remove the hyperlinks entirely if it's just pointing to the team page.

**Comment by hshuaib90** [comment]
> @hshuaib90 what was the long term plan for team pages, were we to have a page each with a bit about us and what we focus on, or is the team page enough? I think we should remove the hyperlinks entirely if it's just pointing to the team page.

The plan was for each of us to have a profile page and it would show the projects we are involved in as well as blogs we have published. I still want to keep this capability but let's see what the rest of the team think. @GSTT-CSC/core ?

**Comment by AnilMistry** [comment]
I'm happy to have this capability. It woulkd also be great to display our names+pictures+profileLink on each article we author on the website, like you see on blogs/news articles.

**Comment by laurencejackson** [comment]
Yeah i think this is a good idea! The only thing I would want to insist on though is that we find a reliable way to make sure our list of blogs/projects/etc updates automatically. Just so we can ensure everything stays current.

**Pull request closed without merging**
