### PR TITLE
changed pic size

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
picture looked stretched, I changed the dimensions of it.

### CODE REVIEW

**Comment by hshuaib90** [comment]
Thanks Lu. Can you remove the Gemfile.lock file please and just commit the jpeg?

**Comment by Lucrezia-Cester** [comment]
deleted the gemfile.lock file

**Review by hshuaib90 — CHANGES_REQUESTED** [review]
Sorry Lu, instead of deleting the Gemfile.lock file you need to just not commit your version of it. It might be easier to create a new branch and only commit your new picture.

**Comment by Lucrezia-Cester** [comment]
I hard deleted the commits and force pushed the branch.

**Review by hshuaib90 — APPROVED** [review]

**Pull request merged**
