### PR TITLE
Lu added profile pic + updated team.yml

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**

### CODE REVIEW

**Comment by hshuaib90** [comment]
Hi @Lucrezia-Cester  - can you edit the name of the Pull Request to something more informative. Have a look at the other PRs (including the closed ones) for good examples.

**Comment by dangerdika** [comment]
models pages were added to this commit by accident, delete them from this commit and i'll review it :)

**Review by hshuaib90 — CHANGES_REQUESTED** [review]
Thanks, Lu, this is great - however, I think you've accidentally added the models' files to this branch. Can you delete these from this branch and recommit, then I can merge them! 🙂

**Comment by hshuaib90** [comment]
@Lucrezia-Cester - can you have a look at this today so I can merge?

**Comment by Lucrezia-Cester** [comment]
removed the 2 extra commits.

**Review by hshuaib90 — APPROVED** [review]

**Pull request merged**
